services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pokemon
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pokemon"]
      interval: 3s
      timeout: 3s
      retries: 30
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/pokemon
      PORT: 3000
    ports: ["3000:3000"]
    command: ["node","dist/main.js"]

  migrate:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/pokemon
    command: ["node","node_modules/.bin/mikro-orm","migration:up"]
    profiles: ["migrate"]

  seed:
    build: .
    depends_on:
      api:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/pokemon
    command: ["node","dist/src/seed/run.js"]
    profiles: ["seed"]

volumes:
  dbdata:
